# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import docker_django.apps.todo.validators
import jsoneditor.fields.postgres_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doortype',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='transition',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterModelOptions(
            name='zonemodel',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='doortype',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doortype',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='item',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='location',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='transition',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transition',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='zone',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AddField(
            model_name='zonemodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zonemodel',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='zonemodel',
            name='model',
            field=jsoneditor.fields.postgres_jsonfield.JSONField(validators=[docker_django.apps.todo.validators.validate_zone], verbose_name='Model'),
        ),
    ]
